apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: mariadb-deployment
spec: # specification for deployment resource
  replicas: 1 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: mariadb
  template: # blueprint for pods
    metadata:
      labels:
        app: mariadb # service will look for this label
    spec: # specification for pods
      containers: # we can have one or more containers
      - name: mariadb
        image: mariadb:11.8.3
        ports:
        - containerPort: 3306
        env:
        #- name: MARIADB_RANDOM_ROOT_PASSWORD
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: seafile-secret
              key: INIT_SEAFILE_MYSQL_ROOT_PASSWORD
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mariadb-data
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
