apiVersion: v1
data:
  INIT_SEAFILE_ADMIN_EMAIL: PHJlcXVpcmVkPg==
  INIT_SEAFILE_ADMIN_PASSWORD: PHJlcXVpcmVkPg==
  INIT_SEAFILE_MYSQL_ROOT_PASSWORD: PHJlcXVpcmVkPg==
  JWT_PRIVATE_KEY: PHJlcXVpcmVkPg==
  REDIS_PASSWORD: ""
  SEAFILE_MYSQL_DB_HOST: YXNkZg==
  SEAFILE_MYSQL_DB_PASSWORD: PHJlcXVpcmVkPg==
  SEAFILE_MYSQL_DB_USER: YXNkZg==
kind: Secret
metadata:
  name: seafile-secret
  namespace: seafile
