apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data # Un nombre para la petición de almacenamiento
  namespace: seafile
spec:
  storageClassName: local-path-prod # O el que estés usando
  accessModes:
    - ReadWriteOnce # El volumen solo puede ser usado por un pod a la vez
  resources:
    requests:
      storage: 5Gi # El tamaño del "disco duro" para la base de datos
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb # Este es el nombre DNS que usará Seafile para conectarse
  namespace: seafile
spec:
  selector:
    app: mariadb # Busca los pods con esta etiqueta (la de tu Deployment de MariaDB)
  ports:
    - protocol: TCP
      port: 3306       # El puerto del servicio
      targetPort: 3306 # El puerto del contenedor de MariaDB
  type: ClusterIP # Solo accesible desde dentro del clúster, que es lo que quieres
