apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: n8n
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  strategy: {}
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - image: n8nio/n8n:1.111.0
        name: n8n
        ports:
          - containerPort: 5678
        volumeMounts:
          - mountPath: /home/node/.n8n
            name: n8n-data
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data
