apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  namespace: adguard
spec:
  type: NodePort
  selector:
    app: adguard-home
  ports:
    - port: 3000
      nodePort: 30030
      targetPort: 3000
      protocol: TCP
      name: http-initial      