persistence:
  homarr-config:
    # -- Enable homarr-config persistent storage
    enabled: true
    # -- homarr-config storage class name
    storageClassName: "local-path"
    # -- homarr-config access mode
    accessMode: "ReadWriteOnce"
    # -- homarr-config storage size
    size: "50Mi"
    # -- homarr-config mount path inside the pod
    mountPath: "/app/data/configs"
  homarr-database:
    # -- Enable homarr-database persistent storage
    enabled: true
    # -- homarr-database storage class name
    storageClassName: "local-path"
    # -- homarr-database access mode
    accessMode: "ReadWriteOnce"
    # -- homarr-database storage size
    size: "50Mi"
    # -- homarr-database mount path inside the pod
    mountPath: "/app/database"
  homarr-icons:
    # -- Enable homarr-icons persistent storage
    enabled: true
    # -- homarr-icons storage class name
    storageClassName: "local-path"
    # -- homarr-icons access mode
    accessMode: "ReadWriteOnce"
    # -- homarr-icons storage size
    size: "50Mi"
    # -- homarr-icons mount path inside the pod
    mountPath: "/app/public/icons"
envSecrets:
  dbCredentials:
    # -- Name of existing secret containing DB credentials
    existingSecret: "db-secret"
    # -- Secret key for SECRET_ENCRYPTION_KEY
    # can be generated with `openssl rand -hex 32`
    dbEncryptionKey: "db-encryption-key"