apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: adguard-pool
  namespace: metallb
spec:
  # Ejemplo: Un rango de 192.168.1.240 a 192.168.1.249
  addresses:
  - 192.168.1.250-192.168.1.254 
#  autoAssign: false
  serviceAllocation:
    namespaces:
      - adguard
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: adguard-l2-advertisement
  namespace: metallb
spec:
  # Vincula este anuncio (L2) al pool de direcciones que definimos arriba
  ipAddressPools:
  - adguard-pool
